language: ruby
rvm:
  - 2.1.8
  - 2.2.4
  - 2.3.0
gemfile:
  - Gemfile
before_install: 
  - gem install bundler -v 1.11.2

script:
  - bundle exec rake db:migrate RAILS_ENV=test
  - bundle exec rspec
